%Generating 6.5D curve with MATLAB and JULIA

%% Step 1: Generate Data
addpath(genpath('./Utility/'));

numPts = 300;
[rMat,T, K, EGT,DPointsOnImage, p1ImageOnImage, p2ImageOnImage] = generateRandomCameraAndPoints(numPts, 0, 0, 10);

expPoints = 7;
P1 = p1ImageOnImage(:,1:expPoints);
P2 = p2ImageOnImage(:,1:expPoints);

pgt(:,:,1) = P1';
pgt(:,:,2) = P2';

[str_gt, ~] = generateDataFor65Dcurve(P1,P2);


%% Step 2: Copy str_gt to Julia, replacing "real_data" line (line 15) then run curve65D.jl for generating curve files


%Julia Part: Run curve65D.jl


%% Step 3: Read the curve file generated by Julia and draw the curve
curve = loadCurves();
figure;
plot(P2(1,1:6),P2(2,1:6),'g.','MarkerSize',30); hold on
plot(P2(1,7),P2(2,7),'r.','MarkerSize',30); hold on
xlim([0,640])
ylim([0,480])
plot(curve(1,:),curve(2,:),'r.'); hold on
set(findall(gcf,'-property','FontSize'),'FontSize',25)